version: 0.2
phases:
  pre_build:
    commands:
      - echo httpd status
      - sudo systemctl status httpd

  build:
    commands:
      - echo Build started on `date`
      - sudo cp ./index.html /var/www/html/index.html
 
