version: 0.2
 
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo httpd status
      - sudo systemctl status httpd

  build:
    commands:
      - echo Build started on `date`
      - sudo cp ./index.html /var/www/html/index.html
   
artifacts:
  type: 
  files:
    - index.html
    - appspec.yml
    - scripts/install_dependencies
    - scripts/start_server
